Technology-Fundamentals-with-CSharp/Web Project/Forum/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Models
{
    public class Category
    {
        public Category()
        {
            Topics = new List<Topic>();
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Category Name")]
        public string Name { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }
        public ApplicationUser Author { get; set; }

        public List<Topic> Topics { get; set; }

        [NotMapped]
        public int NumberTopics => Topics.Count;

        public bool IsAuthor(string id)
        {
            return Author.UserName.Equals(id);
        }
    }
}

Technology-Fundamentals-with-CSharp/Web Project/Forum/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum.Data;
using Forum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Forum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ForumDbContext context;

        public CategoryController(ForumDbContext context)
        {
            this.context = context;
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Category category)
        {
            string authorId = context.Users
                .Where(u => u.UserName == User.Identity.Name)
                .First()
                .Id;

            category.AuthorId = authorId;

            if (ModelState.IsValid)
            {
                context.Categories.Add(category);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Category category = context.Categories
                .Include(t => t.Author)
                .Include(t => t.Topics)
                .ThenInclude(c => c.Author)
                .Where(t => t.Id == id)
                .FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Category> categories = context.Categories
                .Include(c => c.Topics)
                .ToList();

            ViewData["Categories"] = categories;
            return View(category);
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Category category = context.Categories
                .Where(c => c.Id == id)
                .FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (category.IsAuthor(User.Identity.Name))
            {
                return Forbid();
            }

            return View(category);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                Category categoryFromDb = context.Categories
                    .FirstOrDefault(c => c.Id == category.Id);

                if (categoryFromDb != null)
                {
                    categoryFromDb.Name = category.Name;
                    context.SaveChanges();
                }

                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Category category = context.Categories
                .FirstOrDefault(c => c.Id == id);

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            Category category = context.Categories
                .FirstOrDefault(c => c.Id == id);

            if (category != null)
            {
                context.Categories.Remove(category);
                context.SaveChanges();
            }

            return RedirectPermanent("/");
        }
    }
}

Technology-Fundamentals-with-CSharp/Web Project/Forum/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Forum.Data;
using Forum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Forum.Controllers
{
    public class TopicController : Controller
    {
        private readonly ForumDbContext context;

        public TopicController(ForumDbContext context)
        {
            this.context = context;
        }

        //GET: Topic/Details/id
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Topic topic = context.Topics
                .Include(t => t.Author)
                .Include(t => t.Category)
                .Include(t => t.Comments)
                .ThenInclude(c => c.Author)
                .Where(x => x.Id == id)
                .FirstOrDefault();

            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        //GET: Topic/Create
        [Authorize]
        public IActionResult Create()
        {
            var categoryNames = context.Categories
                .Select(c => c.Name)
                .ToList();

            ViewData["CategoryNames"] = categoryNames;

            return View();
        }

        //POST: Topic/Create
        [HttpPost]
        [Authorize]
        public IActionResult Create(string categoryName, Topic topic)
        {
            if (ModelState.IsValid)
            {
                //set CreatedDate and LastUpdatedDate
                topic.CreatedDate = DateTime.Now;
                topic.LastUpdatedDate = DateTime.Now;

                //get user id
                string authorId = context.Users
                    .Where(x => x.UserName == this.User.Identity.Name)
                    .First()
                    .Id;

                //set topic author id
                topic.AuthorId = authorId;

                if (!context.Categories.Any(c => c.Name == categoryName))
                {
                    return View(topic);
                }

                int categoryId = context.Categories
                    .FirstOrDefault(c => c.Name == categoryName)
                    .Id;

                topic.CategoryId = categoryId;

                //save topic
                context.Topics.Add(topic);
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        //GET: Topic/Delete/id
        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var topic = context.Topics
                .Include(x => x.Author)
                .FirstOrDefault(x => x.Id == id);

            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(topic);
        }

        //POST: Topic/Delete/id
        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            //get topic
            var topic = context.Topics
                .Include(x => x.Author)
                .FirstOrDefault(x => x.Id == id);

            //check if topic exists
            if (topic != null)
            {
                //delete topic
                context.Topics.Remove(topic);
                context.SaveChanges();
            }

            // redirect to Index
            return RedirectToAction("Index", "Home");
        }

        //GET: Topic/Edit/id
        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            //get topic from DB
            var topic = context.Topics
                .Include(t => t.Author)
                .Include(t => t.Category)
                .Where(t => t.Id == id)
                .FirstOrDefault();

            //check if topic exists
            if (topic == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (topic.IsAuthor(User.Identity.Name))
            {
                return Forbid();
            }

            var categoryNames = context.Categories
                .Select(c => c.Name)
                .ToList();

            ViewData["CategoryNames"] = categoryNames;

            //pass the model to View
            return View(topic);
        }

        //POST: Topic/Edit/id
        [HttpPost]
        [Authorize]
        public IActionResult Edit(string categoryName, Topic topic)
        {
            if (ModelState.IsValid)
            {
                //get the topic from the DB
                var topicFromDb = context.Topics
                    .Include(x => x.Author)
                    .FirstOrDefault(x => x.Id == topic.Id);

                //check if the topic exists
                if (topicFromDb == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                //set new properties
                topicFromDb.Description = topic.Description;
                topicFromDb.Title = topic.Title;

                int categoryId = context.Categories
                    .FirstOrDefault(c => c.Name == categoryName)
                    .Id;

                topicFromDb.CategoryId = categoryId;

                topicFromDb.LastUpdatedDate = DateTime.Now;

                //save changes
                context.SaveChanges();

                //redirect to Index
                return RedirectToAction("Index", "Home");
            }

            //if model is invalid return the sam topic
            return View(topic);
        }
    }
}

Technology-Fundamentals-with-CSharp/Web Project/Forum/Views/Category/Create.cshtml
@model Category

@{
    ViewData["Title"] = "Create";
}

<h2>Create New Category</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
                <a asp-controller="Home" asp-action="Index" class="btn btn-default">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Technology-Fundamentals-with-CSharp/Web Project/Forum/Views/Category/Delete.cshtml
@model Category

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete the category?</h3>

<div>
    <article class="forum-post post-item highlighted-post">
        <div class="head-post table-holder">
            <div class="post-content">
                <div>
                    <h1>@Model.Name</h1>
                </div>
            </div>
        </div>
    </article>
    <div>
        <form asp-action="Delete">
            <input type="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Delete" class="btn btn-default" />
            <a class="btn btn-default" asp-controller="Home" , asp-action="Index">Cancel</a>
        </form>
    </div>
</div>

Technology-Fundamentals-with-CSharp/Web Project/Forum/Views/Category/Details.cshtml
@model Category

@{
    List<Category> categories = (List<Category>)ViewData["Categories"];
}

<div class="container-fluid">
    <div class="row forum-container">
        <aside class="col-md-3 col-sm-12 forum-sidebar">
            <div class="category-wrapper">
                <p>
                    <a asp-controller="Category" asp-action="Create" class="btn btn-default">Create New Category</a>
                </p>

                <h3>Categories</h3>
                <ul>
                    <li>
                        <a asp-controller="Home" asp-action="Index">All Topics</a>
                    </li>
                    @foreach (var category in categories)
                    {
                        <li>
                            <a asp-controller="Category" asp-action="Details" asp-route-id="@category.Id" class="">@category.Name</a>
                            <span>(@category.NumberTopics)</span>
                        </li>
                    }
                </ul>
            </div>
        </aside>


        <section class="col-md-9 col-sm-12 article-wrapper">
            <p>
                <a asp-controller="Topic" asp-action="Create" class="btn btn-default">Create New Topic</a>
                @if (Model.IsAuthor(User.Identity.Name))
                {
                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-default">Edit</a>
                    <a asp-controller="Category" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-default">Delete</a>
                }

            </p>

            @foreach (var topic in Model.Topics
                                     .OrderByDescending(t => t.CreatedDate)
                                     .ThenByDescending(t => t.LastUpdatedDate))
            {
                <article class="forum-post">
                    <div class="head-post">
                        <h2 class="post-title">
                            <a asp-controller="Topic" asp-action="Details" asp-route-id="@topic.Id">@topic.Title</a>
                        </h2>
                        <p>
                            <span class="user-wrap">
                                <span class="cell">
                                    <span class="user-name">Author: @topic.Author.UserName</span>
                                </span>
                            </span>
                            <span class="user-wrap">
                                <span class="cell">
                                    <span class="user-name">Created Date: @topic.CreatedDate.ToString("HH:mm dd/MMM/yyyy")</span>
                                </span>
                            </span>
                            <span class="user-wrap">
                                <span class="cell">
                                    Category: <a asp-controller="Category" asp-action="Details" asp-route-id="@topic.CategoryId">@topic.Category.Name</a>
                                </span>
                            </span>
                        </p>
                    </div>
                    <div class="meta-info">
                        <div class="col-md-6 last-replay">
                            <div class="table-holder">
                                <div class="last-replay-inner cell">
                                    <span class="cell">Last activity: </span>
                                    <span class="cell replay-date">@topic.LastUpdatedDate.ToString("HH:mm dd/MMM/yyyy")</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 stats-holder">
                            <span class="item-wrap">
                                <span class="cell">Comments: </span>
                                <span class="cell">@topic.NumberComments</span>
                            </span>
                        </div>
                    </div>
                </article>
            }
        </section>
    </div>
</div>

Technology-Fundamentals-with-CSharp/Web Project/Forum/Views/Category/Edit.cshtml
@model Category
<h2>Edit the @Model.Name Category </h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
                <a asp-controller="Home" asp-action="Index" class="btn btn-default">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}